name: Java Microservice CI

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [service-user, service-order, service-inventory, api-gateway, config-server]

    steps:
    - uses: actions/checkout@v4

    - name: setup java 17
      uses: actions/setup-java@v4
      with:
        java_version: '17'
        distribution: 'temurin'

    - name: Maven Build
      run: mvn -B clean install
      working-directory: ${{ matrix.service }}
